config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
   
  resources :movies do
    collection do
      get :search
    end

    member do
      get :movies_by_genre
    end

    resources :reviews
  end

  resources :reviews

  resources :people

  resources :watchlists do
    member do
      get :next
      get :previous
    end
  end

  resources :profiles

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_casts
	has_many :reviews
	has_many :movie_genres
  has_many :watchlists
  has_one_attached :image
  accepts_nested_attributes_for :movie_casts, :movie_genres, allow_destroy: true, reject_if: :all_blank

  validates :title, length: { minimum: 2 }

  scope :all_genre_movies, ->(genre) { Movie.includes(movie_genres: :genre).where("genres.id = ?", genre).references(:movie_genres, :genres) }

  def added_to_watchlist?(user)
    watchlists.user_watchlist(user).any?
  end

  def self.search(filter, search)
    if filter == 'actor'
      Movie.includes(movie_casts: :person).where("people.name ILIKE ?","#{search}%").references(:movie_casts, :people)
    elsif filter == 'genre'
      Movie.includes(movie_genres: :genre).where("genres.title ILIKE ?","#{search}%").references(:movie_genres, :genres)
    elsif filter == 'movies'
      where("LOWER(title) ILIKE ?","#{search}%")
    end
  end
end

app/models/movie_cast.rb
class MovieCast < ApplicationRecord
  belongs_to :person
  belongs_to :movie
  belongs_to :role
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
  scope :unique, -> {select(:genre_id).distinct}
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :movies
  has_one_attached :image
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

end

app/models/role.rb
class Role < ApplicationRecord
	has_one :movie_cast
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :watchlists
  has_one_attached :image
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  scope :user_watchlist, -> (user) { where('user_id = ?', user.id) }

  scope :next, ->(id) { where("id < ?", id).order(id: :desc).first(10) }
  scope :previous, ->(id) { where("id > ?", id).order(id: :desc).last(10) }
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
    @movies = Movie.all
    @genre_movies = MovieGenre.unique
  end

	def new
		@movie = Movie.new
    @movie.movie_casts.build
    @movie.movie_genres.build 
	end

	def create
		@movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end  
	end

	def show
    @movie = Movie.find(params[:id])
    @movies = Movie.all
  end

	def edit
  	@movie = Movie.find(params[:id])
	end

  def search
    if params[:search].blank?  
      redirect_to root_path
    else
      @movies = Movie.search(params[:filter].downcase, params[:search])
      respond_to do |format|
        format.html
        format.js
      end  
    end
  end

  def movies_by_genre
    @genre_movies = MovieGenre.unique
    @movies = Movie.all_genre_movies(params[:id])
    render :index
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render 'edit'
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :release_date, :play_time, :language, :country, :description, :image, 
      movie_casts_attributes: [:id, :person_id, :role_id],
      movie_genres_attributes: [:id, :genre_id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.create(person_params)
    render 'show'
  end

  def show
    @person = Person.find(params[:id])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to @person
    else
      render 'edit'
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
  end

  private

  def person_params
    params.require(:person).permit(:name, :dob, :gender, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper

   def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: "add_fields " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def option_for_select_role(selected = nil)
    base_option_for_select(Role.all.map{ |role| [role.title, role.id] }, selected)
  end

  def option_for_select_genre(selected = nil)
    base_option_for_select(Genre.all.map{ |genre| [genre.title, genre.id] }, selected)
  end

  def option_for_select_filter(selected = nil)
    base_option_for_select(%w[Movies Genre Actor], selected)
  end

  def movie_cast
    #@movie.movie_casts.order(created_at: :asc).all.map { |cast| [cast.role.title, cast.person.name]}
  end

  def base_option_for_select(options, selected = nil)
    if selected
      options_for_select(options, selected)
    else
      options_for_select(options)
    end  
  end

end

app/helpers/people_helper.rb
module PeopleHelper
  def option_for_select_member(selected = nil)
    options = Person.all.map{ |person| [person.name, person.id] }
    if selected
      options_for_select(options, selected)
    else
      options_for_select(options)
    end  
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/people/edit.html.erb
<%= stylesheet_link_tag "movies" %>

<% if user_signed_in? && current_user.role == 'admin' %>
  <div class="card">
    <h1 class="title">Add Person</h1>
    <%= form_for @person do |f|%>
    <div>
      <%= f.label :name%>
      <%= f.text_field :name %><br>
    </div>
    <div>
      <%= f.label :dob%>
      <%= f.date_field :dob %><br>
    </div>
    <div>
      <%= f.label :gender%>
      <%= f.select(:gender, [ 'Male', 'Female' ], {}, { :class => 'select' }) %><br>
    </div>
    <div>
      <%= f.label :image %>
      <%= f.file_field :image, {:style=>'color:#fff;'} %><br><br>
    </div>
      <%= f.submit "Create", :class => "submit" %>
    <%end%>
  </div>
<% else %>
  <% controller.redirect_to root_path %>
<% end %>

app/views/people/index.html.erb
<%= stylesheet_link_tag "movies" %>

<div style="margin-bottom: 7%;">
  <div class="container">
    <h2></h2>
    <table class="table">
      <thead>
        <th>person_id</th>
        <th>Name</th>
        <th>dob</th>
        <th>Gender</th>
        <th>image</th>
      </thead>

      <tbody>
        <% @people.order(created_at: :asc).each do |person| %>
        <tr>
          <td><%= person.id %></td>
          <td><%= person.name %></td>
          <td><%= person.dob %></td>
          <td><%= person.gender %></td>
          <td><%= image_tag(person.image, :style=>'width:100px;') if person.image.attached? %></td>
          <td> <%= link_to "View", person_path(person.id) %></td>
          <% if user_signed_in? && current_user.role == 'admin' %>
            <td> <%= link_to "Edit", edit_person_path(person.id) %></td>
            <td> <%= link_to "Delete", method: :delete %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/people/new.html.erb
<%= stylesheet_link_tag "movies" %>

<div class="card">
  <h1 class="title">Add Person</h1>
  <%= form_for Person.new do |f|%>
  <div>
    <%= f.label :name%>
    <%= f.text_field :name %><br>
  </div>
  <div>
    <%= f.label :dob%>
    <%= f.date_field :dob %><br>
  </div>
  <div>
    <%= f.label :gender%>
    <%= f.select(:gender, [ 'Male', 'Female' ], {}, { :class => 'select' }) %><br>
  </div>
    <%= f.submit "Create", :class => "submit" %>
  <%end%>
</div>
<br><br><br><br><br><br><br><br><br>

app/views/people/show.html.erb
<%= stylesheet_link_tag "users" %>

<div class="card">
  <div class="fakeimg">
    <%= image_tag(@person.image, :style=>'width: 100%; height: 50%;') if @person.image.attached? %>
  </div>
  <h1 class="title"><%= @person.name %></h1>
  <h4>
    DOB: <%=  @person.dob %>
  </h4>
  <h4>
    Gender : <%= @person.gender %>
  </h4>
  <% if user_signed_in? && current_user.role == 'admin' %>
    <td> <%= link_to "Edit", edit_person_path(@person.id) %></td>
  <% end %>
</div>