config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
   
  resources :movies do
    collection do
      get :search
    end

    member do
      get :movies_by_genre
    end

    resources :reviews
  end

  resources :reviews

  resources :people

  resources :watchlists do
    member do
      get :next
      get :previous
    end
  end

  resources :profiles

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_casts
	has_many :reviews
	has_many :movie_genres
  has_many :watchlists
  has_one_attached :image
  accepts_nested_attributes_for :movie_casts, :movie_genres, allow_destroy: true, reject_if: :all_blank

  validates :title, length: { minimum: 2 }

  scope :all_genre_movies, ->(genre) { Movie.includes(movie_genres: :genre).where("genres.id = ?", genre).references(:movie_genres, :genres) }

  def added_to_watchlist?(user)
    watchlists.user_watchlist(user).any?
  end

  def self.search(filter, search)
    if filter == 'actor'
      Movie.includes(movie_casts: :person).where("people.name ILIKE ?","#{search}%").references(:movie_casts, :people)
    elsif filter == 'genre'
      Movie.includes(movie_genres: :genre).where("genres.title ILIKE ?","#{search}%").references(:movie_genres, :genres)
    elsif filter == 'movies'
      where("LOWER(title) ILIKE ?","#{search}%")
    end
  end
end

app/models/movie_cast.rb
class MovieCast < ApplicationRecord
  belongs_to :person
  belongs_to :movie
  belongs_to :role
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
  scope :unique, -> {select(:genre_id).distinct}
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :movies
  has_one_attached :image
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

end

app/models/role.rb
class Role < ApplicationRecord
	has_one :movie_cast
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :watchlists
  has_one_attached :image
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  scope :user_watchlist, -> (user) { where('user_id = ?', user.id) }

  scope :next, ->(id) { where("id < ?", id).order(id: :desc).first(10) }
  scope :previous, ->(id) { where("id > ?", id).order(id: :desc).last(10) }
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
    @movies = Movie.all
    @genre_movies = MovieGenre.unique
  end

	def new
		@movie = Movie.new
    @movie.movie_casts.build
    @movie.movie_genres.build 
	end

	def create
		@movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end  
	end

	def show
    @movie = Movie.find(params[:id])
    @movies = Movie.all
  end

	def edit
  	@movie = Movie.find(params[:id])
	end

  def search
    if params[:search].blank?  
      redirect_to root_path
    else
      @movies = Movie.search(params[:filter].downcase, params[:search])
      respond_to do |format|
        format.html
        format.js
      end  
    end
  end

  def movies_by_genre
    @genre_movies = MovieGenre.unique
    @movies = Movie.all_genre_movies(params[:id])
    render :index
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render 'edit'
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :release_date, :play_time, :language, :country, :description, :image, 
      movie_casts_attributes: [:id, :person_id, :role_id],
      movie_genres_attributes: [:id, :genre_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper

   def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: "add_fields " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def option_for_select_role(selected = nil)
    base_option_for_select(Role.all.map{ |role| [role.title, role.id] }, selected)
  end

  def option_for_select_genre(selected = nil)
    base_option_for_select(Genre.all.map{ |genre| [genre.title, genre.id] }, selected)
  end

  def option_for_select_filter(selected = nil)
    base_option_for_select(%w[Movies Genre Actor], selected)
  end

  def movie_cast
    #@movie.movie_casts.order(created_at: :asc).all.map { |cast| [cast.role.title, cast.person.name]}
  end

  def base_option_for_select(options, selected = nil)
    if selected
      options_for_select(options, selected)
    else
      options_for_select(options)
    end  
  end

end

app/helpers/people_helper.rb
module PeopleHelper
  def option_for_select_member(selected = nil)
    options = Person.all.map{ |person| [person.name, person.id] }
    if selected
      options_for_select(options, selected)
    else
      options_for_select(options)
    end  
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/movies/_add_cast.html.erb
<%= f.label :movie_casts %>
<%= f.select(:person_id, option_for_select_member) %>
<%= link_to "New", new_people_path, :class => "button glyphicon glyphicon-user" %>
<br><br>
<%#= f.label :roles %>
<%#= f.select(:role_id, option_for_select_role) %><br><br>

<div>
  <%= link_to "Remove", '#', class: "remove_fields" %>
</div>

app/views/movies/_movie.html.erb
<%= form_for @movie, multipart: true do |f|%>
  <%= f.label :title%>
  <%= f.text_field :title %><br><br>

  <%= f.label :release_date%>
  <%= f.date_field :release_date %><br><br>

  <%= f.label :play_time %>
  <%= f.time_field :play_time, :format=>"%H:%M" %><br><br>

  <%= f.label :language %>
  <%= f.text_field :language %><br><br>

  <%= f.label :country %>
  <%= f.text_field :country %><br><br>

  <%= f.label :description %>
  <%= f.text_area :description %><br><br>

  <%= f.label :image %>
  <%= f.file_field :image, {:style=>'color:#fff;'} %><br><br>

  <div class="fields">
    <%= f.fields_for :movie_casts do |person| %>
      <%= person.label :movie_casts %>
      <%= person.select(:person_id, option_for_select_member(person.object.person_id)) %>
      <br><br>
      <%= person.label :roles %>
      <%= person.select(:role_id, option_for_select_role(person.object.role_id)) %>
      <%#= render "movie_cast", f: person %>
    <% end %>
    <%= link_to_add_row('Add', f, :movie_casts, :class => "button glyphicon") %>
    <%= link_to "New", new_person_path, :class => "button glyphicon glyphicon-user" %>
  </div>
  <br>
  
  <%= f.fields_for :movie_genres do |genre| %>
    <%= genre.label :genre %>
    <%= genre.select(:genre_id, option_for_select_genre) %>
  <% end %>
  <br><br>
  <%= f.submit :class => "submit" %>
<%end%>

app/views/movies/_movie_cast.html.erb
<div>
  <%= f.label :movie_casts %>
  <%= f.select(:person_id, option_for_select_member) %>
  <br><br>
  <%= f.label :roles %>
  <%= f.select(:role_id, option_for_select_role) %>

  <%= f.hidden_field :_destroy, as: :hidden %>
  <%= link_to "Delete", '#', class: 'remove_record' %>
</div>

app/views/movies/_search.html.erb
<%= javascript_pack_tag 'change_text' %>
<%= javascript_pack_tag 'search' %>

<% if @movies.empty? %>
  <%= render '/layouts/error' %>
<% else %>
  <div style="margin-bottom: 7%;">
      <div class="container">
        <h2></h2>
        <table class="table">
          <thead>
            <tr>
              <th>Id</th>
              <th>Title</th>
              <th>Release_date</th>
              <th>Description</th>
            </tr>
          </thead>
          <% @movies.each do |movie| %>
            <tbody>
              <tr>
                <td><%= movie.id %></td>
                <td style="text-transform: capitalize;"><%= movie.title %></td>
                <td><%= movie.release_date %></td>
                <td><%= movie.description %></td>
                <td><%= image_tag(movie.image, :style=>'width:100px;') if movie.image.attached? %></td>
                <td><%= link_to "View More", movie_path(movie.id) %></td>
                <td><%= link_to "Review", new_movie_review_path(movie.id)%></td>
                <td><%= link_to "See Reviews", movie_reviews_path(movie.id) %></td>
                <% if user_signed_in? && current_user.role == 'admin' %>
                  <td><%= link_to "Edit", edit_movie_path(movie.id)%></td>
                <%end%>
                <td>
                  <% if user_signed_in? %>
                    <% if movie.added_to_watchlist?(current_user) %> 
                      <%= link_to "Added To Watchlist", "#" %>
                    <% else %>
                      <%= form_for movie.watchlists.build, remote: true do |form|%>
                        <%= form.hidden_field :user_id, value: current_user.id %>
                        <%= form.hidden_field :movie_id %>
                        <%= form.submit "Add to Watchlist", :id => "tag#{movie.id}", :style=>'color:#000;' %>
                      <% end %>
                    <% end %>  
                  <% else %>
                    <%= link_to "Add To Watchlist", new_user_registration_path %>
                  <% end %>
              </td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
  </div>
<% end %>

app/views/movies/edit.html.erb
<%= stylesheet_link_tag "movies" %>
<%= javascript_pack_tag "add_new" %>

<% if user_signed_in? && current_user.role == 'admin' %>
  <div class="card">
    <h1 class="title">Edit Movie</h1>
    <%= render "movie" %>
  </div>
<% else %>
  <% controller.redirect_to root_path %>
<% end %>

app/views/movies/index.html.erb
<%= javascript_pack_tag 'change_text' %>

<% if @movies.empty? %>
  <%= render '/layouts/error' %>
<% else %>
  <%= render '/layouts/imageSlider' %>
  <div style="margin-left: 20%;">
    <% @genre_movies.each do |genre| %>
      <%= link_to "#{genre.genre.title}", movies_by_genre_movie_path(genre.genre_id), :class => "btn btn-success" %>
    <%end%>
  </div>
  <div style="margin-bottom: 7%;">
      <div class="container">
        <h2></h2>
        <table class="table">
          <thead>
            <tr>
              <th>Id</th>
              <th>Title</th>
              <th>Release_date</th>
              <th>Genre</th>
              <th>Description</th>
              <th>Poster</th>
              <th></th>
              <th></th>
              <th></th>
              <% if user_signed_in? && current_user.role == 'admin' %>
                <th></th>
              <%end%>
              <th>Add to Watchlist</th>
            </tr>
          </thead>
          <% @movies.order(created_at: :desc).each do |movie| %>
            <tbody id="myTable">
              <tr>
                <td><%= movie.id %></td>
                <td style="text-transform: capitalize;"><%= movie.title %></td>
                <td><%= movie.release_date %></td>
                <td>
                  <% movie.movie_genres.each do |movie| %>
                    <%= movie.genre.title %>
                  <% end %>
                </td>
                <td><%= movie.description %></td>
                <td><%= image_tag(movie.image, :style=>'width:100px;') if movie.image.attached? %></td>
                <td><%= link_to "More", movie_path(movie.id) %></td>
                <td><%= link_to "Review", new_movie_review_path(movie.id)%></td>
                <td><%= link_to "See Reviews", movie_reviews_path(movie.id) %></td>
                <% if user_signed_in? && current_user.role == 'admin' %>
                  <td><%= link_to "Edit", edit_movie_path(movie.id)%></td>
                <%end%>
                <td>
                  <% if user_signed_in? %>
                    <% if movie.added_to_watchlist?(current_user) %> 
                      <%= link_to '&#9989;'.html_safe, "#", :style=>'font-size:30px; margin-left: 17px;' %>
                    <% else %>
                      <%= form_for movie.watchlists.build, remote: true do |form|%>
                        <%= form.hidden_field :user_id, value: current_user.id %>
                        <%= form.hidden_field :movie_id %>
                        <%= form.submit '&#10010;'.html_safe, :id => "tag#{movie.id}", :style=>'color:black; font-size:30px; margin-left: 17px;' %>
                      <% end %>
                    <% end %>  
                  <% else %>
                    <%= link_to '&#10010;'.html_safe, new_user_registration_path, :style =>'font-size:30px; margin-left: 17px;' %>
                  <% end %>
              </td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
  </div>
<% end %>

app/views/movies/new.html.erb
<%= stylesheet_link_tag "movies" %>
<%= javascript_pack_tag "add_new" %>

<% if @movie.errors.full_messages.any? %>
  <% @movie.errors.full_messages.each do |error_message| %>
    <%= error_message if @movie.errors.full_messages.first == error_message %> <br />
  <% end %>
<% end %>

<% if user_signed_in? && current_user.role == 'admin' %>
  <div class="card">
    <h1 class="title">Add Movie</h1>
    <%= render "movie" %>
  </div>
  <br><br>
<% else %>
  <% controller.redirect_to root_path %>
<% end %>

app/views/movies/search.js.erb
$('#myTable').html("<%= j (render 'search') %>");

//alert("success")

app/views/movies/show.html.erb
<%= stylesheet_link_tag "movies" %>

<% if @movie.errors.full_messages.any? %>
  <% @movie.errors.full_messages.each do |error_message| %>
    <%= error_message if @movie.errors.full_messages.first == error_message %> <br />
  <% end %>
<% end %>

<div class="row">
  <div class="leftcolumn col-sm-8">
    <div class="movie-card">
      <h2 class="title">Title: <%= @movie.title %></h2>
      
      <h5 style="color: #ffffff;">Release date: <%= @movie.release_date %></h5>
    
      <div class="fakeimg"><%= image_tag(@movie.image, :style=>'width: 100%; height: 50%;') if @movie.image.attached? %></div>
      
      <p class="description"><%= @movie.description %></p>
      
      <h4 class="details">Cast & Crew:
        <% if @movie.movie_casts.count > 0 %>
          <div style="margin: 10px;">
            <% @movie.movie_casts.order(created_at: :asc).each do |cast| %>
              <span class="role"> <%= cast.role.title %>:</span>
              <span> <%= cast.person.name %></span>
              <br>
            <% end %>
          </div>
        <% else %>
            No Data Available!!
        <% end %>
      </h4>

      <h4 class="details">Genre: 
        <% if @movie.movie_genres.count > 0 %>
          <% @movie.movie_genres.each do |category| %>
            <%= category.genre.title  %>
          <% end %>
        <% else %>
            <span> No Data Available!! </span>
          <% end %>
      </h4>

      <span class="details">
        <% if user_signed_in? && current_user.role == 'user' %>
          <%= form_for @movie.watchlists.build do |form| %>
            <%= form.hidden_field :user_id, value: current_user.id %>
            <%= form.hidden_field :movie_id %>
            <%= form.submit "Add to Watchlist", :class => 'submit_btn' %>
            <%= link_to "Review", new_review_path(@movies), :class => 'submit_btn' %>
          <% end %>
        <% elsif  user_signed_in? && current_user.role == 'admin' %>
          <%= link_to "Edit", edit_movie_path(@movie), :class => 'submit_btn' %>
        <% else %>
          <%= link_to "Review", new_review_path(@movies), :class => 'submit_btn' %>
          <%= link_to "Add To Watchlist", new_user_registration_path, :class => 'submit_btn' %>
        <% end %>
      </span>
    </div>
  </div>

  <div class="rightcolumn col-sm-4">
    <div class="movie_card">
      <h2 class="title">Also Watch</h2>
      <% @movies.each do |movie| %>
        <p> <%= link_to movie.title, movie_path(movie.id), :style => "color: #ffffff;" %> </p>
      <% end %>
    </div>
  </div>
</div>
      