config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
   
  resources :movies do
    collection do
      get :search
    end

    member do
      get :movies_by_genre
    end

    resources :reviews
  end

  resources :reviews

  resources :people

  resources :watchlists do
    member do
      get :next
      get :previous
    end
  end

  resources :profiles

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_casts
	has_many :reviews
	has_many :movie_genres
  has_many :watchlists
  has_one_attached :image
  accepts_nested_attributes_for :movie_casts, :movie_genres, allow_destroy: true, reject_if: :all_blank

  validates :title, length: { minimum: 2 }

  scope :all_genre_movies, ->(genre) { Movie.includes(movie_genres: :genre).where("genres.id = ?", genre).references(:movie_genres, :genres) }

  def added_to_watchlist?(user)
    watchlists.user_watchlist(user).any?
  end

  def self.search(filter, search)
    if filter == 'actor'
      Movie.includes(movie_casts: :person).where("people.name ILIKE ?","#{search}%").references(:movie_casts, :people)
    elsif filter == 'genre'
      Movie.includes(movie_genres: :genre).where("genres.title ILIKE ?","#{search}%").references(:movie_genres, :genres)
    elsif filter == 'movies'
      where("LOWER(title) ILIKE ?","#{search}%")
    end
  end
end

app/models/movie_cast.rb
class MovieCast < ApplicationRecord
  belongs_to :person
  belongs_to :movie
  belongs_to :role
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
  scope :unique, -> {select(:genre_id).distinct}
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :movies
  has_one_attached :image
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

end

app/models/role.rb
class Role < ApplicationRecord
	has_one :movie_cast
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :watchlists
  has_one_attached :image
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  scope :user_watchlist, -> (user) { where('user_id = ?', user.id) }

  scope :next, ->(id) { where("id < ?", id).order(id: :desc).first(10) }
  scope :previous, ->(id) { where("id > ?", id).order(id: :desc).last(10) }
end

app/helpers/application_helper.rb
module ApplicationHelper

   def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: "add_fields " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def option_for_select_role(selected = nil)
    base_option_for_select(Role.all.map{ |role| [role.title, role.id] }, selected)
  end

  def option_for_select_genre(selected = nil)
    base_option_for_select(Genre.all.map{ |genre| [genre.title, genre.id] }, selected)
  end

  def option_for_select_filter(selected = nil)
    base_option_for_select(%w[Movies Genre Actor], selected)
  end

  def movie_cast
    #@movie.movie_casts.order(created_at: :asc).all.map { |cast| [cast.role.title, cast.person.name]}
  end

  def base_option_for_select(options, selected = nil)
    if selected
      options_for_select(options, selected)
    else
      options_for_select(options)
    end  
  end

end

app/helpers/people_helper.rb
module PeopleHelper
  def option_for_select_member(selected = nil)
    options = Person.all.map{ |person| [person.name, person.id] }
    if selected
      options_for_select(options, selected)
    else
      options_for_select(options)
    end  
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_error.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1 class="error">
                    Oops!</h1>
                <h2 class="error">
                    404 Record Not Found</h2>
                <div class="error-details text">
                    Sorry, an error has occured, Requested page not found!
                </div>
            </div>
        </div>
    </div>
</div>
<br><br><br>

app/views/layouts/_footer.html.erb
<footer class="container-fluid text-center">
  <dir>
    <p style="text-align: center;">@copyright : imbd.com</p>
  </dir>
  <div>
    <a href="#" class="fa fa-facebook"></a>
    <a href="#" class="fa fa-twitter"></a>
    <a href="#" class="fa fa-linkedin"></a>
    <a href="#" class="fa fa-instagram"></a>
  </div>
</footer>

app/views/layouts/_imageSlider.html.erb
<%= stylesheet_link_tag 'slider' %>

<div class="slideshow-container">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    
    <ol class="carousel-indicators">
       <% @movies.each_with_index do |photo, n| %>
         <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
       <% end %>
    </ol>

    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag @movies.last.image, :style=>'width:100%;' %>
      </div>
      <% @movies.drop(1).each do |photo| %>
         <div class="item">
           <%= image_tag photo.image, :style=>'width:100%;' %>
         </div>
      <% end %>
    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<%= javascript_pack_tag 'search' %>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "imdb", root_path, :class => "navbar-brand", :style=>'color:yellow;'%>
    </div>
    <ul class="nav navbar-nav">

      <% if user_signed_in? && current_user.role == 'admin' %>
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">+New <span class="     caret"></span></a>
        <ul class="dropdown-menu">
          <li> <%= link_to "Movie", new_movie_path %> </li>
          <li> <%= link_to "Member", new_person_path %> </li>
        </ul>

        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">View<span class=" caret"> </span></a>
        <ul class="dropdown-menu">
          <li> <%= link_to "Movies", movies_path %> </li>
          <li> <%= link_to "Actors", people_path %> </li>
        </ul>
      <% end %>
      
      <li>
        <% if user_signed_in? %>
          <%= link_to "watchlist", watchlists_path(current_user.id)%>
        <% else %>
          <%= link_to "+watchlist", new_user_registration_path %>
        <% end %>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-form navbar-left">
      <div class="input-group">
      <li>
        <%= form_tag search_movies_path, method: 'get', remote: true do %>    
          <%= select_tag(:filter, option_for_select_filter, :class => 'filter', :id => "filter") %>
          <%= search_field_tag :search, params[:search], placeholder: "Search Movie", :class => "input-group form-control", :id => "search" %>
          <div class="input-group-btn">
            <%= submit_tag "Search", :class => "btn btn-default" %>
           <i class="glyphicon glyphicon-search"></i>
          </div>
        <% end %>
      </li>
    </div>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
         <ul class="nav navbar-nav">
          <li class="dropdown"><a class="dropdown-toggle text" data-toggle="dropdown" href="#"><%= current_user.name %> <span class="    caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'profile', profiles_path, :class => 'navbar-link', :style => "color: #0f0e0e;"%></li>
              <li><%= link_to 'Your Reviews', movie_reviews_path(current_user), :class => 'navbar-link', :style => "color: #0f0e0e;"%></li>
              <li><%= link_to "watchlist", watchlists_path(current_user.id), :class => 'navbar-link', :style => "color: #0f0e0e;"%></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link', :style => "color: #0f0e0e;"%></li>
            </ul>
          </li>
        </ul>
        <li><%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => "glyphicon glyphicon-user" %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path, :class => "glyphicon glyphicon-user" %></li>
        <li><%= link_to "Signup", new_user_registration_path, :class => "glyphicon glyphicon-user" %></li>
      <% end %>
    </ul>
  </div>
</nav>

<div id="myTable">
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoImbd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>
<!--
    <% #if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% #end %>
    <% #if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% #end %>
-->
    <%= render "/layouts/navbar" %>
    <%= yield %>
    <%= render "/layouts/footer" %>
  </body>

</html>